### ISSUE TITLE
"ORA-28547 connection to server failed, probable Oracle Net admin error" since El Capitan

### ISSUE THREAD

**Issue by apeiros** [kubo/ruby-oci8#111]
Hi there
After updating to el capitan, I can no longer connect to oracle using rails (or ruby-oci8 directly).
It fails with `oci8.c:694:in oci8lib_220.bundle: ORA-28547: connection to server failed, probable Oracle Net admin error (OCIError)`  
I can still connect to oracle using SQL Developer, which uses the same tnsnames file (/usr/local/oracle/network/admin/tnsnames.ora).  
I can also connect with sqlplus on the CLI, while the exact same connect-string produces above error with OCI8.new.  
I Installed the instant client following http://www.rubydoc.info/gems/ruby-oci8/file/docs/install-on-osx.md, the part without homebrew. That is, I did all steps:

* download the oracle packages
* create /opt/oracle
* unzipped the files in there
* downloaded and ran fix_oralib.rb
* added $OCI_DIR and updated $ORACLE_HOME
* verified $TNS_ADMIN is correct

Versions:

* ruby -v: ruby 2.2.3p173
* ruby-oci8: 2.2.1
* instantclient-sdk-macos.x64-11.2.0.4.0.zip
* instantclient-sqlplus-macos.x64-11.2.0.4.0.zip
* instantclient-basiclite-macos.x64-11.2.0.4.0.zip
* instantclient-basic-macos.x64-11.2.0.4.0.zip (I tried with basiclite first, installed basic over it when it generated above error)

My env variables are:

    OCI_DIR=/opt/oracle/instantclient_11_2
    TNS_ADMIN=/usr/local/oracle/network/admin
    ORACLE_HOME=/opt/oracle/instantclient_11_2

I verified that the paths are correct using `file $OCI_DIR` and `file $ORACLE_HOME`, to avoid potential typos.
Is there any other information I can provide to help?

**Comment by kubo** [comment]
I reproduced same issue on my mac book air.
I'll check it after tomorrow.

**Comment by kubo** [comment]
Did you install two Oracle instant clients under `/opt/oracle/instantclient_11_2` manually and under `/usr/local/lib` via homebrew?

When Oracle instant clients are in `/opt/oracle/instantclient_11_2` and `/usr/local/lib`,
ruby-oci8 installation script uses the latter even if OCI_DIR points to the former.
(I fixed it by 984be4c8f355cff2917a58dc7aa06a4871881c1d.)

If so, uninstall the latter Oracle instant client and reinstall ruby-oci8.
```
brew uninstall instantclient-basic instantclient-basiclite instantclient-sqlplus instantclient-sdk
export OCI_DIR=/opt/oracle/instantclient_11_2
gem uninstall ruby-oci8
gem install ruby-oci8
```

You can check the the Oracle client location used by ruby-oci8 by the following command.
```
ruby -roci8 -e "p OCI8::Util.dll_path"
```

**Comment by apeiros** [comment]
Yay, solved!
Probably of interest to you: `ruby -roci8 -e "p OCI8::Util.dll_path"` reported `/opt/oracle`. But when I ran `brew uninstall instantclient-basiclite instantclient-sdk` and started `pry -roci8`, it failed with (something akin to) `Library not loaded /usr/local/…`. So I'm not sure OCI8::Util.dll_path is helpful there. Additionally, uninstalling alone was insufficient. I had to rerun the `fix_oralib.rb` script in `/opt/oracle`.

So full solution of the problem for me:

* `brew uninstall instantclient-basic instantclient-basiclite instantclient-sqlplus instantclient-sdk` (if it reports one as "not installed", remove from it the list and run again, brew does NOT uninstall the others if the list contains an uninstalled keg)
* `cd /opt/oracle/instantclient_11_2`
* `curl -O https://raw.githubusercontent.com/kubo/fix_oralib_osx/master/fix_oralib.rb`
* `ruby fix_oralib.rb`
* `gem uninstall ruby-oci8`
* `gem install ruby-oci8`

**Comment by apeiros** [comment]
Additionally I had to delete the gemset in the project. I assume there was still somewhere a cache and ruby-oci8 didn't get properly recompiled.

**Comment by apeiros** [comment]
Forgot the most important: thank you very much @kubo for the quick reply & solution!

**Comment by kubo** [comment]
**Summary:** This issue was the combination of the following three issues.

The first issue is that the instant client basiclite package cannot connect to some Oracle servers.
As far as I checked, I got the following matrix.

client|server|connect result
-------|-------|-------
instant client basic 11.2.0.4|Oracle 11.2.0.1 (*1)|success
instant client basic 11.2.0.4|Oracle 12.1.0.2 (*2)|success
instant client basiclite 11.2.0.4|Oracle 11.2.0.1 (*1)|failure with ORA-28547 
instant client basiclite 11.2.0.4|Oracle 12.1.0.2 (*2)|success
*1 database charset is WE8ISO8859P15.
*2 database charset is AL32UTF8.

I guess that it depends on the database charset but I have not verified it.

The second issue is that applications compiled with Oracle library installed via homebrew
use basiclite NLS data even when basic package is installed since September 2015.
I made a pull request fixing it. (See InstantClientTap/homebrew-instantclient#5)

The third issue is that OCI_DIR is ignored when instant client is in `/usr/local/lib`.
So ruby-oci8 cannot use manually installed instant client as long as instant client
is installed via homebrew on OS X El Captian.
This was fixed in the ruby-oci8 github repository as I told in a former comment.

**Comment by yahonda** [comment]
> I guess that it depends on the database charset but I have not verified it.

FYI. for the first issue Oracle Instant Client Light does not support `WE8ISO8859P15` character set described [here] (https://docs.oracle.com/cd/E11882_01/install.112/e38228/install_overview.htm#CJACDCFD). 

Oracle Instant Client Basic is necessary.

**Comment by sinalpha** [comment]
same issue. solved by  following @apeiros steps.Thank you very much.

**Comment by fruwe** [comment]
same issue here, however, I could fix the problem with those steps, since /opt/oracle does not exist.
env: macosx el capitan, oracle@docker@macos, oracle@gateway@server@mac(port forward)

**Comment by wiki01** [comment]
kubo: I'm have same problem and reinstall oracle client 

instant client basiclite 11.2.0.4 --> instant client basic 11.2.0.4 

and solved 

Thank you very much
