### ISSUE TITLE
Version requirement for ruby is too strict 

### ISSUE THREAD

**Issue by greenfieldtech-davidb** [kubo/ruby-oci8#155]
When installing ruby-oci8 with ruby 2.3.1 you get the error:

```
ERROR:  Error installing ruby-oci8:
	ruby-oci8 requires Ruby version ~> 2.3.0.0.
```

**Comment by kubo** [comment]
Thank you for your PR #156.

I added the version requirement to comply with [this post](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/49578). It said that when teeny version (z of ruby x.y.z) was changed, ABI compatibility broke. But it hasn't been true since [ruby 2.1.0](https://www.ruby-lang.org/en/news/2013/12/21/ruby-version-policy-changes-with-2-1-0/). I fixed `ext/oci8/extconf.rb` and `lib/oci8.rb` to comply with the new policy but I forgot to fix `ruby-oci8.gemspec`.
