### ISSUE TITLE
OCI8 support LDAP authentication for Oracle?

### ISSUE THREAD

**Issue by jliang888** [kubo/ruby-oci8#174]
In MySQL world, we usually use a generic user(say scott) which have ssl-key=scott.pem and ssk-cert=scott.crt on local file system, I can use that to access db via mysql client easily, does OCI8 support it for Oracle? or you have better way?

Thanks.

**Comment by kubo** [comment]
Some people seem to use LDAP authentication and I had received issues about [LDAP symbol conflicts](http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/ldap-auth-and-function-interposition.md). However I don't know how to use it.
If you can use LDAP authentication on sqlplus and you can't on ruby-oci8, it is a ruby-oci8 issue. I'll do my best about it. Otherwise, I could do nothing.

**Comment by jliang888** [comment]
Thanks.
