### ISSUE TITLE
windows install cannot build

### ISSUE THREAD

**Issue by dsisnero** [kubo/ruby-oci8#222]
I need to set platform=ruby for nokogiri to work.  When I include ruby-oci8.  It fails even though I have ORACLE_HOME set correctly

Heres the mkmf.log
https://gist.github.com/dsisnero/12861c95f3a893a3723078f6d91c678a

**Comment by kubo** [comment]
How did you install ruby-oci8?
What version of ruby do you use?

`gem install ruby-oci8` installs a pre-compiled gem on Windows by default. Doesn't it work correctly?

Otherwise, do you have special need to install customized ruby-oci8 by yourself? If so, create a gem package and install it with `--with-runtime-check`.

In the top directory of ruby-oci8 source code.
```
gem build ruby-oci8.gemspec
gem install .\ruby-oci8-{version number, fix here].gem -- --with-runtime-check
```

**Comment by kubo** [comment]
closed due to inactivity
