### ISSUE TITLE
Deadlock situation, 2.1.8 can't compile on OS X ELCapitan, 2.2.0 don't support Oracle9i, Any solution?

### ISSUE THREAD

**Issue by gabrieletassoni** [kubo/ruby-oci8#99]
Hi,
I recently upgraded to OS X EL Capitan, but now I'm in a odd situation which I cannot understand how to get out, I need to work on an old Oracle 9i database, but on OS X El Capitan ruby-oci8 won't compile due to DYLD_ issue, the 2.2.0 version, which compiles well having set OCI_DIR, dropped support for Oracle 9i, how could overcome this deadlock?
Is there a way you can release a 2.1.9 version which reads OCI_DIR and allow for compilation under OS X El Capitan?

Thank you for the answer, best regards,
Gabriele

**Comment by gabrieletassoni** [comment]
Hi,
as a temporary workaround I disabled SIP from OS X Recovery, this way the OS won't check for DYLD_ paths and I'm allowed to compile, it's not the recommended solution, but as a workaround it works, to apply it:

- reboot into recovery (Command + R during boot)
- select Utilities -> Terminal
- type csrutil disable and press enter
- reboot

from now on SIP is disabled and ruby-oci8 can be installed.

**Comment by jamesinfmz** [comment]
Disabling SIP is pretty brute-force. I found [this](https://github.com/kubo/fix_oralib_osx), which fixed the issue for me, without having to disable SIP.

**Comment by kubo** [comment]
@gabrieletassoni 
Could you enable SIP and check whether ruby-oci8 works or not?
If the Oracle 9i installer property fixed shared library identification and install names in
Oracle libraries, ruby-oci8 may work once it was installed successfully.
(SIP must be disabled on ruby-oci8 2.1.8 installation.)

If sqlplus command in the Oracle 9i doesn't run when SIP is enabled, fix identification and install names
by the following commands:
```shell
cd $ORACLE_HOME
cp -rp lib lib.bak # backup
cp -rp bin/sqlplus bin/sqlplub.bak  # ditto

cd $ORACLE_HOME/lib
curl -O https://raw.githubusercontent.com/kubo/fix_oralib_osx/master/fix_oralib.rb
ruby fix_oralib.rb

cd $ORACLE_HOME/bin
ruby ../lib/fix_oralib.rb sqlplus
```
You need to get the latest fix_oralib.rb. I updated it to accept `libclntsh.dylib.9.0`.
https://github.com/kubo/fix_oralib_osx/blob/4f654d093edce44599199dd739e591f602849dae/fix_oralib.rb#L35

If sqlplus doesn't work still, add dependent Oracle library names to `@@oralibs` in fix_oralib.rb and try again. You may need to add `libwtc9.dylib` to `@@oralibs` because `libclntsh.so.9.0` depends on `libwtc9.so` on Linux.

If sqlplus works, fix install names in oci8lib_*.dylib.

Find the gem repository directory.
```shell
gem query -d ruby-oci8
```

Find oci8lib_*.dylib
```shell
find /replace/here/with/gem/repository/directory -name "oci8lib_*.dylib"
```
Fix install names in oci8lib_*.dylib
```
ruby $ORACLE_HOME/lib/fix_oralib.rb /replace/here/with/full/path/of/oci8lib_*.dylib
```

**Comment by gabrieletassoni** [comment]
Thank you for the answers,
@kubo, I will try it tomorrow since I'll start working again on that project tomorrow, just a clarification: "Could you enable SIP and check whether ruby-oci8 works or not?" you are referring to ruby-oci8 2.1.8 still, the 2.2 branch is still not compatible with oracle 9i, right?

Thank you,
Gabriele

**Comment by kubo** [comment]
Yes, I refer to ruby-oci8 2.1.8.
Ruby-oci8 2.2 doesn't support 9i anymore.
Old Oracle clients lack some OCI functions used by ruby-oci8 2.2.

Yet another option is:
```shell
# Download ruby-oci8 2.1.8 and extract it.
curl -OL https://bintray.com/artifact/download/kubo/generic/ruby-oci8-2.1.8.tar.gz
tar xvfz ruby-oci8-2.1.8.tar.gz
cd ruby-oci8-2.1.8
# Update ext/oci8/oraconf.rb to the latest version.
cd ext/oci8
curl -O https://raw.githubusercontent.com/kubo/ruby-oci8/master/ext/oci8/oraconf.rb
cd ../..
# Build a new gem and install it.
gem build ruby-oci8.gemspec
export OCI_DIR=...change here...
gem install ./ruby-oci8-2.1.8.gem
```
You need to check the followings before ruby-oci8 compilation.

Check whether sqlplus works or not when SIP is disabled.
If it doesn't work, use fix_oralib.rb as written in my previous comment.

Check the output of `otool -D $ORACLE_HOME/lib/libclntsh.dylib.9.0 | awk 'FNR==2 {print $1}'`.
If it isn't the real absolute path of libclntsh.dylib.9.0 or `@rpath/libclntsh.dylib.9.0`,
run `install_name_tool -id $ORACLE_HOME/lib/libclntsh.dylib.9.0 $ORACLE_HOME/lib/libclntsh.dylib.9.0` to fix the share library identification name.
